version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bialimac/ponderada4-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: bialimac/ponderada4-frontend
    restart: always
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend